openapi: "3.0.1"

info:
  title: "Library Viewer Backend"
  version: "0.0.1"
  description: API for the Library Viewer Application

servers:
  - url: http://localhost:8080/api
    description: Local server

paths:
  /user:
    $ref: 'paths/user/createUser.yml'

  /user/all:
    $ref: 'paths/user/getAllUsers.yml'

  /user/credentials:
    $ref: 'paths/user/checkUserCredentials.yml'

  /user/email-confirmed:
    $ref: 'paths/user/emailConfirmed.yml'

  /user/resend-email:
    $ref: 'paths/user/resendConfirmationEmail.yml'