openapi: "3.0.1"

info:
  title: "Library Viewer Backend"
  version: "0.0.1"
  description: API for the Library Viewer Application

servers:
  - url: http://localhost:8080/api
    description: Local server

paths:
  /user:
    $ref: 'paths/user/postWithGeneratedId.yml'

  /user/{id}:
    $ref: 'paths/user/postGetDeleteById.yml'

  /user/all:
    $ref: 'paths/user/getAllUsers.yml'
