openapi: "3.0.1"

info:
  title: "Library Viewer Backend"
  version: "0.0.1"
  description: API for the Library Viewer Application

servers:
  - url: http://localhost:8080/api
    description: Local server

paths:
  /user:
    $ref: 'paths/user/createUser.yml'

  /user/all:
    $ref: 'paths/user/getAllUsers.yml'

  /user/credentials:
    $ref: 'paths/user/checkUserCredentials.yml'

  /user/email-confirmed:
    $ref: 'paths/user/emailConfirmed.yml'

  /user/resend-email:
    $ref: 'paths/user/resendConfirmationEmail.yml'

  /book/all:
    $ref: 'paths/book/getAllBooks.yml'

  /book/{id}:
    $ref: 'paths/book/getDeleteBook.yml'

  /book:
    $ref: 'paths/book/addBook.yml'

  /book/cover/{filename}:
    $ref: 'paths/book/getBookCover.yml'

  /book/newly-added/{amount}:
    $ref: 'paths/book/getNewlyAddedBooks.yml'

  /author:
    $ref: 'paths/author/addAuthor.yml'

  /author/{id}:
    $ref: 'paths/author/getDeleteAuthor.yml'

  /author/all:
    $ref: 'paths/author/getAllAuthors.yml'

  /author/picture/{filename}:
    $ref: 'paths/author/getAuthorPicture.yml'

  /author/newly-added/{amount}:
    $ref: 'paths/author/getNewlyAddedAuthors.yml'