insert into reviews ( title, content, created_by, book_id)
values (

           'Review1',
           'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed ullamcorper morbi tincidunt ornare massa. Faucibus scelerisque eleifend donec pretium. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Ultrices in iaculis nunc sed augue lacus. Sollicitudin tempor id eu nisl. Vel fringilla est ullamcorper eget nulla facilisi etiam. Sed elementum tempus egestas sed sed risus pretium quam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Amet nisl purus in mollis. Dictum sit amet justo donec enim. Lectus quam id leo in. A erat nam at lectus urna duis. Quisque sagittis purus sit amet volutpat consequat mauris. Aliquam vestibulum morbi blandit cursus risus at ultrices. Sed tempus urna et pharetra pharetra massa. Amet nisl purus in mollis nunc sed id semper. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Pulvinar sapien et ligula ullamcorper malesuada proin.

   Elit sed vulputate mi sit. Lectus proin nibh nisl condimentum id venenatis a. Eu mi bibendum neque egestas congue quisque egestas diam in. Viverra maecenas accumsan lacus vel facilisis. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Sapien nec sagittis aliquam malesuada bibendum. Posuere morbi leo urna molestie at elementum. Id interdum velit laoreet id donec ultrices tincidunt arcu. Quisque sagittis purus sit amet volutpat. Tortor dignissim convallis aenean et tortor at. Sapien pellentesque habitant morbi tristique senectus. Sem fringilla ut morbi tincidunt augue. Eget arcu dictum varius duis at consectetur lorem.

   Turpis egestas sed tempus urna et pharetra. Vitae congue eu consequat ac felis. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Egestas integer eget aliquet nibh praesent tristique. Turpis egestas sed tempus urna et. Volutpat maecenas volutpat blandit aliquam etiam. Nibh sit amet commodo nulla facilisi nullam vehicula. Arcu non sodales neque sodales ut etiam sit amet. Quisque egestas diam in arcu cursus. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Feugiat scelerisque varius morbi enim nunc faucibus a. Velit euismod in pellentesque massa placerat duis. Amet aliquam id diam maecenas ultricies mi eget mauris. Sed felis eget velit aliquet.

   In tellus integer feugiat scelerisque varius. Eget arcu dictum varius duis. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Mauris cursus mattis molestie a iaculis at erat pellentesque. Vitae tempus quam pellentesque nec nam aliquam. Porttitor eget dolor morbi non. Morbi tristique senectus et netus et malesuada fames. Massa massa ultricies mi quis hendrerit dolor magna eget est. Mauris ultrices eros in cursus turpis massa. Ut morbi tincidunt augue interdum. Arcu non odio euismod lacinia at. A arcu cursus vitae congue mauris rhoncus aenean vel elit. In est ante in nibh mauris cursus mattis molestie. Non pulvinar neque laoreet suspendisse interdum consectetur libero id.',
           '2afa0363-3879-45d3-9450-5323c898c525',
           9788368005066
       );

insert into reviews (title, content, created_by, book_id)
values (

           'Review2',
           'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed ullamcorper morbi tincidunt ornare massa. Faucibus scelerisque eleifend donec pretium. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Ultrices in iaculis nunc sed augue lacus. Sollicitudin tempor id eu nisl. Vel fringilla est ullamcorper eget nulla facilisi etiam. Sed elementum tempus egestas sed sed risus pretium quam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Amet nisl purus in mollis. Dictum sit amet justo donec enim. Lectus quam id leo in. A erat nam at lectus urna duis. Quisque sagittis purus sit amet volutpat consequat mauris. Aliquam vestibulum morbi blandit cursus risus at ultrices. Sed tempus urna et pharetra pharetra massa. Amet nisl purus in mollis nunc sed id semper. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Pulvinar sapien et ligula ullamcorper malesuada proin.

   Elit sed vulputate mi sit. Lectus proin nibh nisl condimentum id venenatis a. Eu mi bibendum neque egestas congue quisque egestas diam in. Viverra maecenas accumsan lacus vel facilisis. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Sapien nec sagittis aliquam malesuada bibendum. Posuere morbi leo urna molestie at elementum. Id interdum velit laoreet id donec ultrices tincidunt arcu. Quisque sagittis purus sit amet volutpat. Tortor dignissim convallis aenean et tortor at. Sapien pellentesque habitant morbi tristique senectus. Sem fringilla ut morbi tincidunt augue. Eget arcu dictum varius duis at consectetur lorem.

   Turpis egestas sed tempus urna et pharetra. Vitae congue eu consequat ac felis. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Egestas integer eget aliquet nibh praesent tristique. Turpis egestas sed tempus urna et. Volutpat maecenas volutpat blandit aliquam etiam. Nibh sit amet commodo nulla facilisi nullam vehicula. Arcu non sodales neque sodales ut etiam sit amet. Quisque egestas diam in arcu cursus. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Feugiat scelerisque varius morbi enim nunc faucibus a. Velit euismod in pellentesque massa placerat duis. Amet aliquam id diam maecenas ultricies mi eget mauris. Sed felis eget velit aliquet.

   In tellus integer feugiat scelerisque varius. Eget arcu dictum varius duis. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Mauris cursus mattis molestie a iaculis at erat pellentesque. Vitae tempus quam pellentesque nec nam aliquam. Porttitor eget dolor morbi non. Morbi tristique senectus et netus et malesuada fames. Massa massa ultricies mi quis hendrerit dolor magna eget est. Mauris ultrices eros in cursus turpis massa. Ut morbi tincidunt augue interdum. Arcu non odio euismod lacinia at. A arcu cursus vitae congue mauris rhoncus aenean vel elit. In est ante in nibh mauris cursus mattis molestie. Non pulvinar neque laoreet suspendisse interdum consectetur libero id.',
           '2afa0363-3879-45d3-9450-5323c898c525',
           9788368005066
       );


insert into reviews (title, content, created_by, book_id)
values (

           'Review3',
           'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed ullamcorper morbi tincidunt ornare massa. Faucibus scelerisque eleifend donec pretium. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Ultrices in iaculis nunc sed augue lacus. Sollicitudin tempor id eu nisl. Vel fringilla est ullamcorper eget nulla facilisi etiam. Sed elementum tempus egestas sed sed risus pretium quam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Amet nisl purus in mollis. Dictum sit amet justo donec enim. Lectus quam id leo in. A erat nam at lectus urna duis. Quisque sagittis purus sit amet volutpat consequat mauris. Aliquam vestibulum morbi blandit cursus risus at ultrices. Sed tempus urna et pharetra pharetra massa. Amet nisl purus in mollis nunc sed id semper. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Pulvinar sapien et ligula ullamcorper malesuada proin.

   Elit sed vulputate mi sit. Lectus proin nibh nisl condimentum id venenatis a. Eu mi bibendum neque egestas congue quisque egestas diam in. Viverra maecenas accumsan lacus vel facilisis. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Sapien nec sagittis aliquam malesuada bibendum. Posuere morbi leo urna molestie at elementum. Id interdum velit laoreet id donec ultrices tincidunt arcu. Quisque sagittis purus sit amet volutpat. Tortor dignissim convallis aenean et tortor at. Sapien pellentesque habitant morbi tristique senectus. Sem fringilla ut morbi tincidunt augue. Eget arcu dictum varius duis at consectetur lorem.

   Turpis egestas sed tempus urna et pharetra. Vitae congue eu consequat ac felis. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Egestas integer eget aliquet nibh praesent tristique. Turpis egestas sed tempus urna et. Volutpat maecenas volutpat blandit aliquam etiam. Nibh sit amet commodo nulla facilisi nullam vehicula. Arcu non sodales neque sodales ut etiam sit amet. Quisque egestas diam in arcu cursus. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Feugiat scelerisque varius morbi enim nunc faucibus a. Velit euismod in pellentesque massa placerat duis. Amet aliquam id diam maecenas ultricies mi eget mauris. Sed felis eget velit aliquet.

   In tellus integer feugiat scelerisque varius. Eget arcu dictum varius duis. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Mauris cursus mattis molestie a iaculis at erat pellentesque. Vitae tempus quam pellentesque nec nam aliquam. Porttitor eget dolor morbi non. Morbi tristique senectus et netus et malesuada fames. Massa massa ultricies mi quis hendrerit dolor magna eget est. Mauris ultrices eros in cursus turpis massa. Ut morbi tincidunt augue interdum. Arcu non odio euismod lacinia at. A arcu cursus vitae congue mauris rhoncus aenean vel elit. In est ante in nibh mauris cursus mattis molestie. Non pulvinar neque laoreet suspendisse interdum consectetur libero id.',
           '2afa0363-3879-45d3-9450-5323c898c525',
           9788368005066
       );


insert into reviews (title, content, created_by, book_id)
values (

           'Review4',
           'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed ullamcorper morbi tincidunt ornare massa. Faucibus scelerisque eleifend donec pretium. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Ultrices in iaculis nunc sed augue lacus. Sollicitudin tempor id eu nisl. Vel fringilla est ullamcorper eget nulla facilisi etiam. Sed elementum tempus egestas sed sed risus pretium quam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Amet nisl purus in mollis. Dictum sit amet justo donec enim. Lectus quam id leo in. A erat nam at lectus urna duis. Quisque sagittis purus sit amet volutpat consequat mauris. Aliquam vestibulum morbi blandit cursus risus at ultrices. Sed tempus urna et pharetra pharetra massa. Amet nisl purus in mollis nunc sed id semper. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Pulvinar sapien et ligula ullamcorper malesuada proin.

   Elit sed vulputate mi sit. Lectus proin nibh nisl condimentum id venenatis a. Eu mi bibendum neque egestas congue quisque egestas diam in. Viverra maecenas accumsan lacus vel facilisis. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Sapien nec sagittis aliquam malesuada bibendum. Posuere morbi leo urna molestie at elementum. Id interdum velit laoreet id donec ultrices tincidunt arcu. Quisque sagittis purus sit amet volutpat. Tortor dignissim convallis aenean et tortor at. Sapien pellentesque habitant morbi tristique senectus. Sem fringilla ut morbi tincidunt augue. Eget arcu dictum varius duis at consectetur lorem.

   Turpis egestas sed tempus urna et pharetra. Vitae congue eu consequat ac felis. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Egestas integer eget aliquet nibh praesent tristique. Turpis egestas sed tempus urna et. Volutpat maecenas volutpat blandit aliquam etiam. Nibh sit amet commodo nulla facilisi nullam vehicula. Arcu non sodales neque sodales ut etiam sit amet. Quisque egestas diam in arcu cursus. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Feugiat scelerisque varius morbi enim nunc faucibus a. Velit euismod in pellentesque massa placerat duis. Amet aliquam id diam maecenas ultricies mi eget mauris. Sed felis eget velit aliquet.

   In tellus integer feugiat scelerisque varius. Eget arcu dictum varius duis. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Mauris cursus mattis molestie a iaculis at erat pellentesque. Vitae tempus quam pellentesque nec nam aliquam. Porttitor eget dolor morbi non. Morbi tristique senectus et netus et malesuada fames. Massa massa ultricies mi quis hendrerit dolor magna eget est. Mauris ultrices eros in cursus turpis massa. Ut morbi tincidunt augue interdum. Arcu non odio euismod lacinia at. A arcu cursus vitae congue mauris rhoncus aenean vel elit. In est ante in nibh mauris cursus mattis molestie. Non pulvinar neque laoreet suspendisse interdum consectetur libero id.',
           '2afa0363-3879-45d3-9450-5323c898c525',
           9788368005066
       );

